import { UnfathomableCharacter } from './UnfathomableCharacter';

export const unfathomableCharacters: ReadonlyArray<UnfathomableCharacter> = [
  {
    name: 'antar al-fakahany',
    expansion: 'from-the-abyss',
    wiedza: 2,
    percepcja: 3,
  },
  { name: 'arjun singh', wplyw: 2, percepcja: 1, sila: 2 },
  {
    name: 'avery engelbrecht',
    expansion: 'from-the-abyss',
    wplyw: 2,
    sila: 2,
    wola: 1,
  },
  { name: 'beatrice sharpe', wplyw: 1, wiedza: 2, percepcja: 2 },
  {
    name: 'edmund mallory',
    wplyw: 1,
    wiedza: 1,
    percepcja: 1,
    sila: 1,
    wola: 1,
  },
  {
    name: 'guillaume delacroix',
    expansion: 'from-the-abyss',
    wplyw: 2,
    wiedza: 2,
    wola: 1,
  },
  {
    name: 'ida lawrence',
    expansion: 'from-the-abyss',
    wplyw: 2,
    wiedza: 1,
    sila: 2,
  },
  { name: 'ismael marsh', wiedza: 2, sila: 2, wola: 1 },
  { name: 'jamie snell', sila: 3, wola: 2 },
  { name: 'jeanne lafarge', wplyw: 1, percepcja: 2, sila: 2 },
  { name: 'keilani tatupu', wplyw: 3, wola: 2 },
  {
    name: 'sardaana morgunova',
    expansion: 'from-the-abyss',
    wplyw: 2,
    percepcja: 2,
    wola: 1,
  },
  { name: 'kokoj fernandes', expansion: 'from-the-abyss', wiedza: 2, wola: 3 },
  {
    name: 'raul martinez garcia',
    expansion: 'from-the-abyss',
    wiedza: 1,
    percepcja: 2,
    sila: 2,
  },
  { name: 'samira dualeh', wiedza: 1, percepcja: 2, wola: 2 },
  { name: 'svetlana gedroits', wplyw: 2, wiedza: 1, percepcja: 2 },
  { name: 'william bowleg', wiedza: 3, wola: 2 },
  {
    name: 'wong mui choo',
    expansion: 'from-the-abyss',
    percepcja: 1,
    sila: 2,
    wola: 2,
  },
];
